language:
- ruby
sudo: required
branches:
  only:
  - master
  
install:
- sudo add-apt-repository ppa:texlive-backports/ppa -y
- sudo apt-get update -y -q
- sudo apt-get install texlive-latex-extra -y -q
- sudo apt-get install texlive-luatex -y -q
- sudo apt-get install texlive-fonts-extra -y -q
- sudo apt-get install cm-super -y -q
- sudo apt-get install texlive-bibtex-extra -y -q
- sudo apt-get install latexmk -y -q
- sudo apt-get install tex4ht -y -q
- sudo apt-get install texlive-fonts-recommended  -y -q
- wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
- sudo texlua install-getnonfreefonts
- sudo getnonfreefonts-sys garamond

script:
- latexmk -pdflatex='pdflatex -interaction=nonstopmode' -pdf